# Generated by Django 2.1.2 on 2018-10-19 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20181012_1250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='minPrice',
            new_name='min_price',
        ),
    ]
