# Generated by Django 2.1.2 on 2018-10-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20181019_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='leader',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AlterField(
            model_name='auction',
            name='author',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='auction',
            name='state',
            field=models.CharField(choices=[(0, 'Active'), (1, 'Banned'), (2, 'Due'), (3, 'Adjudicated')], default='Active', max_length=20),
        ),
    ]
