# Generated by Django 2.1.2 on 2018-10-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20181020_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='leader',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
