# Generated by Django 2.1.2 on 2018-10-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20181020_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='leader',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
